version: '3.8'
services:
  appseed-app:
    container_name: appseed_app
    restart: always
    env_file: .env
    build: .
    volumes:
      - ./:/app/
      - ./staticfiles/admin:/usr/share/nginx/html/static/admin
      - ./staticfiles/rest_framework:/usr/share/nginx/html/static/rest_framework
      - ./staticfiles/summernote:/usr/share/nginx/html/static/summernote
      - ./media:/media
    networks:
      - db_network
      - web_network
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /var/www/html:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt
      - ./staticfiles/admin:/usr/share/nginx/html/static/admin
      - ./staticfiles/rest_framework:/usr/share/nginx/html/static/rest_framework
      - ./staticfiles/summernote:/usr/share/nginx/html/static/summernote
      - ./media:/usr/share/nginx/html/media
      
    networks:
      - web_network
    depends_on: 
      - appseed-app
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
 