# Generated by Django 3.2.13 on 2022-09-05 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('note_text', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон')),
                ('t_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='telegram_token')),
                ('t_start_phrases', models.CharField(blank=True, max_length=500, null=True, verbose_name='Фраза приветствия в telegram')),
                ('datetime1', models.DateTimeField(blank=True, null=True, verbose_name='Время начала')),
                ('datetime2', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('slot', models.IntegerField(default=60, verbose_name='Длина слота (в мин)')),
                ('its_1', models.BooleanField(default=True, verbose_name='Понедельник')),
                ('its_2', models.BooleanField(default=True, verbose_name='Вторник')),
                ('its_3', models.BooleanField(default=True, verbose_name='Среда')),
                ('its_4', models.BooleanField(default=True, verbose_name='Четверг')),
                ('its_5', models.BooleanField(default=True, verbose_name='Пятница')),
                ('its_6', models.BooleanField(default=True, verbose_name='Суббота')),
                ('its_7', models.BooleanField(default=True, verbose_name='Воскресенье')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('typeOrg', models.CharField(blank=True, choices=[('NON', 'Другое'), ('CAR', 'Автосервис'), ('BUI', 'Салон красоты'), ('STO', 'Стоматология')], default='NOT', max_length=10, null=True, verbose_name='Тип организации')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Орг',
                'verbose_name_plural': 'Орг',
            },
        ),
        migrations.CreateModel(
            name='OrgService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование')),
                ('note_text', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('time_min', models.IntegerField(default=0, verbose_name='Время в минутах')),
                ('time_clean', models.BooleanField(default=False, verbose_name='Требуется чистка')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.org', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'ОргУслуги',
                'verbose_name_plural': 'ОргУслуги',
            },
        ),
        migrations.CreateModel(
            name='OrgWorkers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(default=0, verbose_name='chat_id')),
                ('t_id', models.IntegerField(default=0, verbose_name='t_id')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('note_text', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('moderation', models.BooleanField(default=False, verbose_name='Прошел модерацию')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.org', verbose_name='Организация')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь в системе')),
            ],
            options={
                'verbose_name': 'ОргМастера',
                'verbose_name_plural': 'ОргМастера',
            },
        ),
        migrations.CreateModel(
            name='SprFieldTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование поля')),
                ('order', models.IntegerField(default=0, verbose_name='Сортировка')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
            ],
            options={
                'verbose_name': 'ШаблонПолейДляВсехОрганизаций',
                'verbose_name_plural': 'ШаблонПолейДляВсехОрганизаций',
            },
        ),
        migrations.CreateModel(
            name='OrgWorkersOrgService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k', models.DecimalField(decimal_places=2, default=1.0, max_digits=6, verbose_name='Коэфициент наценки(1,00)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('org_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.orgservice', verbose_name='Услуга')),
                ('org_workers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.orgworkers', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'ОргМастераУслуги',
                'verbose_name_plural': 'ОргМастераУслуги',
            },
        ),
        migrations.CreateModel(
            name='OrgWorkerPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='orgWorkFile/', verbose_name='Фото')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('org_workers_org_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.orgworkersorgservice', verbose_name='ОрганизацияМастера')),
            ],
            options={
                'verbose_name': 'ОргФотоМастеров',
                'verbose_name_plural': 'ОргФотоМастеров',
            },
        ),
        migrations.CreateModel(
            name='OrgUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(default=0, verbose_name='chat_id')),
                ('field_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование поля')),
                ('field_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Значение')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.org', verbose_name='Организация')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь в системе')),
            ],
            options={
                'verbose_name': 'ОргКлиенты',
                'verbose_name_plural': 'ОргКлиенты',
            },
        ),
        migrations.CreateModel(
            name='OrgServicePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='orgServiceFile/', verbose_name='Фото')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('org_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.orgservice', verbose_name='ОрганизацияУслуги')),
            ],
            options={
                'verbose_name': 'ОргУслугиФото',
                'verbose_name_plural': 'ОргУслугиФото',
            },
        ),
        migrations.CreateModel(
            name='OrgPlanTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.org', verbose_name='Организация')),
                ('org_workers_org_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.orgworkersorgservice', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'ОргПланРабот',
                'verbose_name_plural': 'ОргПланРабот',
            },
        ),
        migrations.CreateModel(
            name='OrgFieldTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование поля')),
                ('order', models.IntegerField(default=0, verbose_name='Сортировка')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.org', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'ОргШаблонВвода',
                'verbose_name_plural': 'ОргШаблонВвода',
            },
        ),
        migrations.CreateModel(
            name='OrgBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование')),
                ('note_text', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.org', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'ОргБокс',
                'verbose_name_plural': 'ОргБокс',
            },
        ),
    ]
