# Generated by Django 3.2.13 on 2022-09-05 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgworkerphoto',
            options={'verbose_name': 'ОргФотоСпециалистов', 'verbose_name_plural': 'ОргФотоСпециалистов'},
        ),
        migrations.AlterModelOptions(
            name='orgworkers',
            options={'verbose_name': 'ОргСпециалиста', 'verbose_name_plural': 'ОргСпециалиста'},
        ),
        migrations.AlterModelOptions(
            name='orgworkersorgservice',
            options={'verbose_name': 'ОргСпециалистаУслуги', 'verbose_name_plural': 'ОргСпециалистаУслуги'},
        ),
        migrations.AlterField(
            model_name='org',
            name='t_start_phrases',
            field=models.TextField(blank=True, null=True, verbose_name='Фраза приветствия в telegram'),
        ),
        migrations.AlterField(
            model_name='orgworkerphoto',
            name='org_workers_org_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.orgworkersorgservice', verbose_name='ОрганизацияСпециалиста'),
        ),
        migrations.AlterField(
            model_name='orgworkersorgservice',
            name='org_workers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.orgworkers', verbose_name='Специалист'),
        ),
    ]
