# Generated by Django 3.2.13 on 2022-09-07 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220905_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_string', models.CharField(blank=True, max_length=255, null=True, verbose_name='ДатаСтрокой')),
                ('h_string', models.CharField(blank=True, max_length=255, null=True, verbose_name='ВремяСтрокой')),
                ('d_datetime', models.DateTimeField(auto_now=True, verbose_name='ДатаЗаписи')),
                ('user_id', models.IntegerField(default=0, verbose_name='t_user_id')),
                ('chat_id', models.IntegerField(default=0, verbose_name='t_chat_id')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.org', verbose_name='Организация')),
                ('org_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.orgservice', verbose_name='ОрганизацияУслуги')),
                ('org_workers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.orgworkers', verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'ШаблонПолейДляВсехОрганизаций',
                'verbose_name_plural': 'ШаблонПолейДляВсехОрганизаций',
            },
        ),
    ]
