# Generated by Django 3.2.13 on 2022-09-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_sheduler'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sheduler',
            options={'verbose_name': 'Записи', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AddField(
            model_name='org',
            name='datetime_string_end',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='ВремяОкончанияСтрокой'),
        ),
        migrations.AddField(
            model_name='org',
            name='datetime_string_start',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='ВремяНачалаСтрокой'),
        ),
        migrations.AlterField(
            model_name='sheduler',
            name='d_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ДатаЗаписи'),
        ),
    ]
