# Generated by Django 3.2.13 on 2022-09-08 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220908_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='org',
            name='datetime1',
        ),
        migrations.RemoveField(
            model_name='org',
            name='datetime2',
        ),
    ]
