# Generated by Django 3.2.13 on 2022-10-18 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0007_auto_20220909_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortUrl', models.CharField(blank=True, max_length=255, null=True, verbose_name='КороткаяСсылка')),
                ('longUrl', models.CharField(blank=True, max_length=255, null=True, verbose_name='ДлиннаяСсылка')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ссылки',
                'verbose_name_plural': 'Ссылки',
            },
        ),
        migrations.RemoveField(
            model_name='org',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orgbox',
            name='org',
        ),
        migrations.RemoveField(
            model_name='orgfieldtemplate',
            name='org',
        ),
        migrations.RemoveField(
            model_name='orgplantime',
            name='org',
        ),
        migrations.RemoveField(
            model_name='orgplantime',
            name='org_workers_org_service',
        ),
        migrations.RemoveField(
            model_name='orgservice',
            name='org',
        ),
        migrations.RemoveField(
            model_name='orgservicephoto',
            name='org_service',
        ),
        migrations.RemoveField(
            model_name='orguser',
            name='org',
        ),
        migrations.RemoveField(
            model_name='orguser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orgworkerphoto',
            name='org_workers_org_service',
        ),
        migrations.RemoveField(
            model_name='orgworkers',
            name='org',
        ),
        migrations.RemoveField(
            model_name='orgworkers',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orgworkersorgservice',
            name='org_service',
        ),
        migrations.RemoveField(
            model_name='orgworkersorgservice',
            name='org_workers',
        ),
        migrations.RemoveField(
            model_name='sheduler',
            name='org',
        ),
        migrations.RemoveField(
            model_name='sheduler',
            name='org_service',
        ),
        migrations.RemoveField(
            model_name='sheduler',
            name='org_workers',
        ),
        migrations.DeleteModel(
            name='SprFieldTemplate',
        ),
        migrations.DeleteModel(
            name='Org',
        ),
        migrations.DeleteModel(
            name='OrgBox',
        ),
        migrations.DeleteModel(
            name='OrgFieldTemplate',
        ),
        migrations.DeleteModel(
            name='OrgPlanTime',
        ),
        migrations.DeleteModel(
            name='OrgService',
        ),
        migrations.DeleteModel(
            name='OrgServicePhoto',
        ),
        migrations.DeleteModel(
            name='OrgUser',
        ),
        migrations.DeleteModel(
            name='OrgWorkerPhoto',
        ),
        migrations.DeleteModel(
            name='OrgWorkers',
        ),
        migrations.DeleteModel(
            name='OrgWorkersOrgService',
        ),
        migrations.DeleteModel(
            name='Sheduler',
        ),
    ]
