# Generated by Django 3.2.13 on 2022-10-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_urlbase_typesource'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlbase',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Количество открытий'),
        ),
    ]
