# Generated by Django 3.2.13 on 2022-11-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_urlbase_longurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlbase',
            name='longUrl',
            field=models.CharField(blank=True, max_length=2083, null=True, verbose_name='Исходная ссылка'),
        ),
    ]
