# Generated by Django 3.2.13 on 2022-11-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_urlbase_longurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlbase',
            name='img_svg',
            field=models.ImageField(blank=True, null=True, upload_to='QR', verbose_name='QR'),
        ),
    ]
