# Generated by Django 3.2.13 on 2022-11-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_urlbase_img_svg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlbase',
            name='img_svg',
            field=models.FileField(blank=True, null=True, upload_to='QR', verbose_name='QR'),
        ),
    ]
