# Generated by Django 3.2.13 on 2022-11-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_urlbase_img_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlbase',
            name='typeDevice',
            field=models.CharField(blank=True, choices=[('none', 'none'), ('mobile', 'mobile'), ('tablet', 'tablet'), ('pc', 'pc')], default='none', max_length=10, null=True, verbose_name='Тип устройства'),
        ),
        migrations.AddField(
            model_name='urlbase',
            name='userIP',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IP'),
        ),
    ]
