# Generated by Django 3.2.13 on 2022-11-30 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortDescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Короткое описание')),
                ('itsOn', models.BooleanField(default=False, verbose_name='Активна')),
                ('dateStart', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала')),
                ('dateEnd', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('countPoint', models.IntegerField(default=0, verbose_name='Количество баллов')),
                ('dateEndPoint', models.DateTimeField(blank=True, null=True, verbose_name='Срок действия баллов')),
                ('limitCountOn', models.IntegerField(default=0, verbose_name='Максимальное число активаций')),
                ('emailZone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email зона')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
            ],
            options={
                'verbose_name': 'Акции',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stringPromo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Строчка промо')),
                ('itsOn', models.BooleanField(default=False, verbose_name='Активен')),
                ('dateStart', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('dateEnd', models.DateTimeField(blank=True, null=True, verbose_name='Срок действия')),
                ('limitCountOn', models.IntegerField(default=0, verbose_name='Максимальное число активаций')),
                ('currentCountOn', models.IntegerField(default=0, verbose_name='Максимальное число активаций')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='email')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.action', verbose_name='Акция')),
            ],
            options={
                'verbose_name': 'ПромоКоды',
                'verbose_name_plural': 'ПромоКоды',
            },
        ),
        migrations.CreateModel(
            name='PromoOnList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stringPromo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Строчка промо')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='телефон')),
                ('dateOn', models.DateTimeField(auto_now=True, verbose_name='Дата активации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.promo', verbose_name='ПромоКод')),
            ],
            options={
                'verbose_name': 'ПромоКоды',
                'verbose_name_plural': 'ПромоКоды',
            },
        ),
    ]
