# Generated by Django 3.2.13 on 2022-11-30 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_action_promo_promoonlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promoonlist',
            options={'verbose_name': 'ПромоКодыАктивация', 'verbose_name_plural': 'ПромоКодыАктивация'},
        ),
    ]
