# Generated by Django 3.2.13 on 2022-11-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_promoonlist_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='currentCountOn',
            field=models.IntegerField(default=0, verbose_name='Текущее число активаций'),
        ),
    ]
