# Generated by Django 3.2.13 on 2023-08-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_promo_currentcounton'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlbase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created date'),
        ),
    ]
