# Generated by Django 3.2.13 on 2025-02-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_urlbase_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.JSONField(blank=True, null=True, verbose_name='Ключевые слова')),
            ],
            options={
                'verbose_name': 'Ключевые слова CEO',
                'verbose_name_plural': 'Ключевые слова CEO',
            },
        ),
    ]
